language: go

os:
  - linux

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get update
 - sudo apt-get install -qq lxc lxc-dev uidmap
 - echo "${USER}:100000:65536" | sudo tee /etc/subuid
 - echo "${USER}:100000:65536" | sudo tee /etc/subgid
 - mkdir -p ~/.config/lxc/
 - cp /etc/lxc/default.conf ~/.config/lxc/default.conf
 - echo "lxc.id_map = u 0 100000 65536" | sudo tee -a ~/.config/lxc/default.conf
 - echo "lxc.id_map = g 0 100000 65536" | sudo tee -a ~/.config/lxc/default.conf

install:
  - go get gopkg.in/lxc/go-lxc.v2

script:
  - "make all"
  - "make test"
  - "make test-race"
  - "make test-unprivileged"
  - "make test-unprivileged-race"
  - "make cover"

notifications:
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
